"""added name

Revision ID: 8033215648f6
Revises: cf4ef79c428f
Create Date: 2023-04-06 11:39:19.792784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8033215648f6'
down_revision = 'cf4ef79c428f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('baker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baker', sa.INTEGER(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
